# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Checkout CiviCRM
        uses: actions/checkout@v2
        repository: WeMoveEU/wemove-civicrm
        ref: civicrm-5.35.1.patched
        path: drupal/sites/all/modules
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout extension
        uses: actions/checkout@v2
        path: drupal/sites/all/modules/civicrm/ext

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          php --version
          phpunit --version
