# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      
      - name: Install dependencies
        run: sudo apt install php-bcmath php-calendar php-ctype php-curl php-dom php-exif php-fileinfo php-ftp php-gd php-gettext php-iconv php-igbinary php-imagick php-intl php-json php-mbstring php-mysqli php-mysqlnd php-opcache php-pdo php-phar php-posix php-readline php-redis php-shmop php-simplexml php-soap php-sockets php-sysvmsg php-sysvsem php-sysvshm php-tokenizer php-wddx php-xdebug php-xml php-xmlreader php-xmlwriter php-xsl php-zip
      
      - name: Install Drush
      - uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://github.com/drush-ops/drush/releases/download/8.4.5/drush.phar
          file-name: drush
          location: ./bin/
      - run: chmod +x ./bin/drush
        
      - name: Download Drupal
        run: ./bin/drush dl drupal-7.80 --destination=. --drupal-project-rename

      - name: Checkout CiviCRM
        uses: actions/checkout@v2
        with:
          repository: WeMoveEU/wemove-civicrm
          ref: civicrm-5.35.1.patched
          path: drupal/sites/all/modules
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout extension
        uses: actions/checkout@v2
        with:
          path: drupal/sites/all/modules/civicrm/ext

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          php --version
          phpunit --version
          head -20 drupal/includes/bootsrap.inc
