# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      
      - name: Install dependencies
        run: sudo apt install php8.0-bcmath php8.0-calendar php8.0-ctype php8.0-curl php8.0-dom php8.0-exif php8.0-fileinfo php8.0-ftp php8.0-gd php8.0-gettext php8.0-iconv php8.0-igbinary php8.0-imagick php8.0-intl php8.0-json php8.0-mbstring php8.0-mysqli php8.0-mysqlnd php8.0-opcache php8.0-pdo php8.0-phar php8.0-posix php8.0-readline php8.0-redis php8.0-shmop php8.0-simplexml php8.0-soap php8.0-sockets php8.0-sysvmsg php8.0-sysvsem php8.0-sysvshm php8.0-tokenizer php8.0-wddx php8.0-xdebug php8.0-xml php8.0-xmlreader php8.0-xmlwriter php8.0-xsl php8.0-zip
      
      - name: Install Drush
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://github.com/drush-ops/drush/releases/download/8.4.5/drush.phar
          file-name: drush
          location: ./bin/
      - run: chmod +x ./bin/drush
        
      - name: Download Drupal
        run: ./bin/drush dl drupal-7.80 --destination=. --drupal-project-rename

      - name: Checkout CiviCRM
        uses: actions/checkout@v2
        with:
          repository: WeMoveEU/wemove-civicrm
          ref: civicrm-5.35.1.patched
          path: drupal/sites/all/modules
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout extension
        uses: actions/checkout@v2
        with:
          path: drupal/sites/all/modules/civicrm/ext

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          php --version
          phpunit --version
          head -20 drupal/includes/bootsrap.inc
