# This is a basic workflow to help you get started with Actions

name: Run tests

env:
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    environment: testing

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install wemove-civicrm
        uses: WeMoveEU/wemove-civicrm@gh-action

      - name: Checkout required extensions
        uses: actions/checkout@v2
        with:
          repository: WeMoveEU/eu.wemove.gidipirus
          path: drupal/sites/all/modules/civicrm/ext/gidipirus
      - uses: actions/checkout@v2
        with:
          repository: WeMoveEU/contributm
          path: drupal/sites/all/modules/civicrm/ext/contributm
      - uses: actions/checkout@v2
        with:
          repository: WeMoveEU/org.project60.sepa
          ref: 1.5.0.patched
          path: drupal/sites/all/modules/civicrm/ext/sepa
      - uses: sudosubin/git-clone-action@v1.0.1
        with:
          platform: lab.civicrm.org
          repository: extensions/mjwshared
          ref: master
          path: drupal/sites/all/modules/civicrm/ext/mjwshared
      - uses: actions/checkout@v2
        with:
          repository: WeMoveEU/com.drastikbydesign.stripe
          ref: wemove-6.5.7
          path: drupal/sites/all/modules/civicrm/ext/stripe
      - uses: actions/checkout@v2
        with:
          repository: WeMoveEU/commitcivi.git
          ref: master
          path: drupal/sites/all/modules/civicrm/ext/commitcivi

      - name: Install dependencies' dependencies...
        run: composer install
        working-directory: drupal/sites/all/modules/civicrm/ext/sepa/packages

      - name: Checkout this extension
        uses: actions/checkout@v2
        with:
          path: drupal/sites/all/modules/civicrm/ext/we-act

      - name: Run composer
        run: composer install
        working-directory: drupal/sites/all/modules/civicrm/ext/we-act

      - name: Run unit tests
        run: STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} phpunit
        working-directory: drupal/sites/all/modules/civicrm/ext/we-act


