# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    env:
      php_version: '7.3'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Set PHP version
        run: sudo ln -sf /usr/bin/php${php_version} /usr/bin/php

      - name: Install dependencies
        run: sudo apt install php${php_version}-bcmath php${php_version}-calendar php${php_version}-ctype php${php_version}-curl php${php_version}-dom php${php_version}-exif php${php_version}-fileinfo php${php_version}-ftp php${php_version}-gd php${php_version}-gettext php${php_version}-iconv php${php_version}-igbinary php${php_version}-imagick php${php_version}-intl php${php_version}-mbstring php${php_version}-mysqli php${php_version}-mysqlnd php${php_version}-opcache php${php_version}-pdo php${php_version}-phar php${php_version}-posix php${php_version}-readline php${php_version}-redis php${php_version}-shmop php${php_version}-simplexml php${php_version}-soap php${php_version}-sockets php${php_version}-sysvmsg php${php_version}-sysvsem php${php_version}-sysvshm php${php_version}-tokenizer  php${php_version}-xdebug php${php_version}-xml php${php_version}-xmlreader php${php_version}-xmlwriter php${php_version}-xsl php${php_version}-zip

      - name: Install Drush
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://github.com/drush-ops/drush/releases/download/8.4.5/drush.phar
          file-name: drush
          location: ./bin/
      - run: chmod +x ./bin/drush

      - name: Download Drupal
        run: ./bin/drush dl drupal-7.80 --destination=./ --drupal-project-rename

      - name: Checkout CiviCRM
        uses: actions/checkout@v2
        with:
          repository: WeMoveEU/wemove-civicrm
          ref: civicrm-5.35.1.patched
          path: drupal/sites/all/modules

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout extension
        uses: actions/checkout@v2
        with:
          path: drupal/sites/all/modules/civicrm/ext/we-act
      
      - name: Run unit tests
        run: phpunit
        working-directory: drupal/sites/all/modules/civicrm/ext/we-act

